### PR TITLE
fix: patch dataloader to propagate context to new fiber

### LINKED ISSUE #127: GraphQL dataloaders not compatible with opentelemetry tracing plugin
Ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin20]
GraphQL Gem Version: 2.0.13

Options `enable_platform_field` and `enable_platform_authorized` are not compatible with GraphQL gem's own fiber based dataloaders. Turning on these options while using the built-in dataloaders results in missing data and logs like:
~~~
ERROR -- : OpenTelemetry error: calls to detach should match corresponding calls to attach.
ERROR -- : OpenTelemetry error: calls to detach should match corresponding calls to attach.
ERROR -- : OpenTelemetry error: calls to detach should match corresponding calls to attach.
ERROR -- : OpenTelemetry error: calls to detach should match corresponding calls to attach.
ERROR -- : OpenTelemetry error: calls to detach should match corresponding calls to attach.
ERROR -- : OpenTelemetry error: calls to detach should match corresponding calls to attach.
~~~

I'm assuming this has to do with [the way these data loaders work](https://graphql-ruby.org/dataloader/adopting.html). Somehow, this appeared to be working fine while using [NewRelic tracing](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/tracing/new_relic_tracing.rb) and it was able to capture traces with details on field hops and authorizations. Removing the dataloaders fixes this problem, but we need them to prevent N+1 query issues.

~~~ruby
# field method
def team
  dataloader.with(Sources::Record, Team).load(object.team_id)
end

# authorized? method
def self.authorized?(object, context)
  can_access_team?(context.dataloader.with(Sources::Record, Team).load(object.team_id))
end
~~~

### PR DESCRIPTION
**Pull request by xuanduc987**
I think this should fix #127

### CODE REVIEW

File: instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb [hunk 1]
```diff
@@ -96,6 +98,13 @@ def install_new_tracer(config = {})
             end
           end
         end
+
+        def patch
+          return if gem_version < Gem::Version.new('2.1.8')
```
Comment (xuanduc987) [inline instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb]: The target of the patch, `Dataloader#spawn_fiber` method existed from version 2.1.8

**Comment by rmosolgo** [comment]
LGTM :+1:

File: instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb (hunk 1 above)
Comment (arielvalentin) [reply instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb]: Ideally we would have some automated tests that test this functionality to avoid regressions. 

@rmosolgo do you have any recommendations on how to set up a test to cover this?

Comment (xuanduc987) [reply instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb]: I had added a test for the expected behavior of `#spawn_fiber`.
I also confirmed that it failed without the patch.

**Review by arielvalentin — APPROVED** [review]
