### PR TITLE
fix: do not expose auth params with Redis 5

### LINKED ISSUE #953: Redis Gem 5.x Support
The instrumentation only supports the Redis 4.x.

https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/8863073727/job/24336701986?pr=951

```console
1) Failure:
  OpenTelemetry::Instrumentation::Redis::Patches::RedisV4Client::#process::when db_statement is :omit#test_0001_omits db.statement attribute [test/opentelemetry/instrumentation/redis/patches/client_test.rb:300]:
  Expected: "AUTH"
    Actual: "PIPELINED"
  
    2) Error:
  OpenTelemetry::Instrumentation::Redis::Middlewares::RedisClientInstrumentation::#process#test_0009_records net.peer.name and net.peer.port attributes:
  NoMethodError: undefined method `name' for nil
      test/opentelemetry/instrumentation/redis_client_test.rb:163:in `block (3 levels) in <top (required)>'
  
    3) Failure:
  OpenTelemetry::Instrumentation::Redis::Middlewares::RedisClientInstrumentation::#process#test_0004_after authorization with Redis server [test/opentelemetry/instrumentation/redis_client_test.rb:70]:
  Expected: "AUTH ?"
    Actual: "AUTH passw0rd"
  
    4) Failure:
  OpenTelemetry::Instrumentation::Redis::Patches::RedisV4Client::#process#test_0008_records exceptions [test/opentelemetry/instrumentation/redis/patches/client_test.rb:153]:
  Expected "Unhandled exception of type: RedisClient::CommandError" to include "ERR unknown command 'THIS_IS_NOT_A_REDIS_FUNC', with args beginning with: 'THIS_IS_NOT_A_VALID_ARG".
  
    5) Error:
  OpenTelemetry::Instrumentation::Redis::Patches::RedisV4Client::#process#test_0015_truncates long db.statements:
  Redis::CommandError: ERR unknown command `queue`, with args beginning with: `set`, `v1`, `yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy`, (redis://localhost:6379)
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client/connection_mixin.rb:36:in `call'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client.rb:294:in `block (2 levels) in call_v'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client/middlewares.rb:16:in `call'
      lib/opentelemetry/instrumentation/redis/middlewares/redis_client.rb:25:in `block in call'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `block in with_span'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/context.rb:87:in `with_value'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `with_span'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
      lib/opentelemetry/instrumentation/redis/middlewares/redis_client.rb:24:in `call'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client.rb:293:in `block in call_v'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client.rb:699:in `ensure_connected'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client.rb:292:in `call_v'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-5.2.0/lib/redis/client.rb:90:in `call_v'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-5.2.0/lib/redis.rb:152:in `block in send_command'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-5.2.0/lib/redis.rb:[151](https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/8862991669/job/24336536178#step:4:161):in `synchronize'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-5.2.0/lib/redis.rb:151:in `send_command'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-5.2.0/lib/redis/commands.rb:234:in `method_missing'
      test/opentelemetry/instrumentation/redis/patches/client_test.rb:228:in `block (3 levels) in <top (required)>'
  
    6) Error:
  OpenTelemetry::Instrumentation::Redis::Patches::RedisV4Client::#process#test_0011_traces pipelined commands on commit:
  Redis::CommandError: ERR unknown command `queue`, with args beginning with: `set`, `v1`, `0`, (redis://localhost:6379)
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client/connection_mixin.rb:36:in `call'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client.rb:294:in `block (2 levels) in call_v'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client/middlewares.rb:16:in `call'
      lib/opentelemetry/instrumentation/redis/middlewares/redis_client.rb:25:in `block in call'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `block in with_span'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/context.rb:87:in `with_value'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `with_span'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
      lib/opentelemetry/instrumentation/redis/middlewares/redis_client.rb:24:in `call'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client.rb:293:in `block in call_v'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client.rb:699:in `ensure_connected'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-client-0.22.1/lib/redis_client.rb:292:in `call_v'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-5.2.0/lib/redis/client.rb:90:in `call_v'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-5.2.0/lib/redis.rb:[152](https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/8862991669/job/24336536178#step:4:162):in `block in send_command'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-5.2.0/lib/redis.rb:151:in `synchronize'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-5.2.0/lib/redis.rb:151:in `send_command'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/redis-5.2.0/lib/redis/commands.rb:234:in `method_missing'
      test/opentelemetry/instrumentation/redis/patches/client_test.rb:188:in `block (3 levels) in <top (required)>'
  
    7) Failure:
  OpenTelemetry::Instrumentation::Redis::Patches::RedisV4Client::#process#test_0006_reflects db index [test/opentelemetry/instrumentation/redis/patches/client_test.rb:101]:
  Expected: 3
    Actual: 2
  
    8) Error:
  OpenTelemetry::Instrumentation::Redis::Patches::RedisV4Client::#process#test_0009_records net.peer.name and net.peer.port attributes:
  NoMethodError: undefined method `name' for nil
      test/opentelemetry/instrumentation/redis/patches/client_test.rb:[163](https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/8862991669/job/24336536178#step:4:173):in `block (3 levels) in <top (required)>'
  
    9) Failure:
  OpenTelemetry::Instrumentation::Redis::Patches::RedisV4Client::#process#test_0004_after authorization with Redis server [test/opentelemetry/instrumentation/redis/patches/client_test.rb:70]:
  Expected: "AUTH ?"
    Actual: "AUTH passw0rd"
  
   10) Failure:
  OpenTelemetry::Instrumentation::Redis::Patches::RedisV4Client::#process::when db_statement is :obfuscate#test_0001_obfuscates arguments in db.statement [test/opentelemetry/instrumentation/redis/patches/client_test.rb:329]:
  Expected: "AUTH"
    Actual: "PIPELINED"
  
  50 runs, 178 assertions, 6 failures, 4 errors, 0 skips
  rake aborted!
  Command failed with status (1)
  /opt/hostedtoolcache/Ruby/3.3.0/x64/bin/bundle:25:in `load'
  /opt/hostedtoolcache/Ruby/3.3.0/x64/bin/bundle:25:in `<main>'
  Tasks: TOP => test
  (See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by zvkemp**
Redis 5 is a wrapper around RedisClient, so the middleware-based instrumentation (intended for RedisClient) applies here.

- The largest issue this fixes is that AUTH params are exposed as span attributes at runtime when using Redis 5. Redis commands are not case sensitive, so making the matcher insensitive corrects the issue.
- Other changes are test-only:
  - the expectations found in [instrumentation/redis/test/opentelemetry/instrumentation/redis/patches/client_test.rb](https://github.com/open-telemetry/opentelemetry-ruby-contrib/compare/main...zvkemp:redis-5.x?expand=1#diff-299ab64880b7a183e857381007b2c6bee8a1c11fd5eb7a4e4388d328c06a2641) largely apply to Redis v4 and Redis v5 equally, though technically the patches are not the thing under test for Redis v5. It's possible this file should be renamed; it may be more clear to group the tests based on their API rather than which patch/middleware applies.
  - The expectations that do not apply equally have been branched using a `redis_gte_5?` helper method.
  - `queue` method invocations (deprecated in v4, removed in v5) have been replaced with `pipelined`
  - Several of the middleware tests (i.e. [instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb](https://github.com/open-telemetry/opentelemetry-ruby-contrib/compare/main...zvkemp:redis-5.x?expand=1#diff-a8d5160de5742f85fa7ff24b06e16cc3e2879b3836a243198b8b7248ea799811)) were not being run with the correct RedisClient api (when using Redis v4, `Redis.new` does **not** use RedisClient internally).

### CODE REVIEW

File: instrumentation/redis/test/opentelemetry/instrumentation/redis/patches/client_test.rb [hunk 1]
```diff
@@ -297,7 +338,7 @@ def redis_with_auth(redis_options = {})
         _(exporter.finished_spans.size).must_equal 3
 
         set_span = exporter.finished_spans[0]
-        _(set_span.name).must_equal 'AUTH'
+        _(set_span.name).must_equal(redis_gte_5? ? 'PIPELINED' : 'AUTH')
```
Comment (arielvalentin) [inline instrumentation/redis/test/opentelemetry/instrumentation/redis/patches/client_test.rb:341]: We may want to look into splitting these tests up. I know it will lead to duplication but conditional logic in tests that go beyond using `skip` become difficult to reason about IMO.

File: instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb [hunk 2]
```diff
@@ -21,10 +21,12 @@
   # will generate one extra span on connect because the Redis client will
   # send an AUTH command before doing anything else.
   def redis_with_auth(redis_options = {})
-    redis_options[:password] = password
-    redis_options[:host] = redis_host
-    redis_options[:port] = redis_port
-    RedisClient.new(**redis_options)
+    redis_options[:password] ||= password
```
Comment (arielvalentin) [inline instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb:24]: Why are these lazily initialized?

**Review by arielvalentin — APPROVED** [review]

File: instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb [hunk 3]
```diff
@@ -157,9 +183,10 @@ def redis_with_auth(redis_options = {})
 
     it 'records net.peer.name and net.peer.port attributes' do
       expect do
-        Redis.new(host: 'example.com', port: 8321, timeout: 0.01).auth(password)
-      end.must_raise Redis::CannotConnectError
+        redis_with_auth(host: 'example.com', port: 8321, timeout: 0.01)
+      end.must_raise RedisClient::CannotConnectError
 
+      skip('FIXME: what is this intended to test?')
```
Comment (arielvalentin) [inline instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb:189]: I missed this `skip` during my last review. 

I think what the intent was was to ensure the span had the `net.peer.*` attributes where captured during a network failure to execute the `auth` command. 

Are there changes in how the driver works that would make this impossible to do?

**Review by arielvalentin — CHANGES_REQUESTED** [review]

File: instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb (hunk 3 above)
Comment (zvkemp) [reply instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb:189]: Ah yes, forgot to follow up on that one. RedisClient tries to do the connect before any of the middlewares are invoked, so we don't get a span here under that implementation. I don't think it's within the scope of the PR to change that behavior (previously, the test was erroneously running the RedisV4 client instrumentation), but I didn't want to complete clobber the expectations (these still exist in the other test file). I can clarify the comment so that if that span _is_ ever added for RedisClient, it should have those attributes.

File: instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb (hunk 2 above)
Comment (zvkemp) [reply instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb:24]: Seemed appropriate not to clobber the options from the argument if they are given — the `redis_with_auth(host: 'example.com' ...` test fails without this.

File: instrumentation/redis/test/opentelemetry/instrumentation/redis/patches/client_test.rb (hunk 1 above)
Comment (zvkemp) [reply instrumentation/redis/test/opentelemetry/instrumentation/redis/patches/client_test.rb:341]: Do you mean to individually duplicate the tests that should be forked, or duplicate the file entirely for v5?

**Comment by zvkemp** [comment]
@arielvalentin thanks for your feedback; I clarified some of the test changes.

File: instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb (hunk 3 above)
Comment (arielvalentin) [reply instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb]: I see. In that case then I think it's fine to delete the test since we won't be able to get a span generated from it.

**Review by kaylareopelle — APPROVED** [review]
Thanks for your work on this, @zvkemp!

> it may be more clear to group the tests based on their API rather than which patch/middleware applies.

I like this idea. I don't think refactoring the tests needs to be accomplished in this PR. What do you think about opening an issue to save this work for a future date?

**Review by arielvalentin — APPROVED** [review]
